server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tflow?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456.com

    jackson:
      #字段为null时不返回该字段
      default-property-inclusion: non_null
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss

#日志配置
logging:
  level:
    root: info

#mybatis配置
mybatis-plus:
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
